import './style/index.css'
export * from './utils/color.ts'
export type * from './utils/types.ts'

export { useVModel } from './composables/useVModel.ts'
export { parseHex } from './utils/parsers.ts'
export { createUiSlots } from './utils/styles.ts'
export type { Styling, VanillaClassFn, UiSliderSlots, UiInputSlots } from './utils/styles.ts'
export { SVG_MOSAIC_URL } from './utils/consts.ts'
export { injectColorPickerContext } from './components/ColorPickerRoot.vue'

export { default as ColorPickerRoot } from './components/ColorPickerRoot.vue'
export { default as ColorPickerCanvas } from './components/ColorPickerCanvas.vue'
export { default as ColorPickerEyeDropper } from './components/ColorPickerEyeDropper.vue'
export { default as ColorPickerInputHex } from './components/ColorPickerInputHex.vue'
export { default as ColorPickerInputRGB } from './components/ColorPickerInputRGB.vue'
export { default as ColorPickerInputHSL } from './components/ColorPickerInputHSL.vue'
export { default as ColorPickerInputHSB } from './components/ColorPickerInputHSB.vue'
export { default as ColorPickerSliderAlpha } from './components/ColorPickerSliderAlpha.vue'
export { default as ColorPickerSliderHue } from './components/ColorPickerSliderHue.vue'
export { default as ColorPickerSliderSaturation } from './components/ColorPickerSliderSaturation.vue'
export { default as ColorPickerSliderLightness } from './components/ColorPickerSliderLightness.vue'
export { default as ColorPickerSliderRed } from './components/ColorPickerSliderRed.vue'
export { default as ColorPickerSliderGreen } from './components/ColorPickerSliderGreen.vue'
export { default as ColorPickerSliderBlue } from './components/ColorPickerSliderBlue.vue'
export { default as ColorPickerSwatch } from './components/ColorPickerSwatch.vue'

export type { ColorPickerRootProps, ColorPickerRootEmits } from './components/ColorPickerRoot.vue'
