<script lang="ts">
export interface GradientPickerPositionInputProps {
  /** Stop to edit; defaults to the selected stop. */
  stopId?: number,
  label?: string,
  class?: string,
  ui?: Partial<{
    group: string
    item: string
    field: string
  }>
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { clampPosition } from '../core/stops.ts'
import { injectGradientPickerContext } from './GradientPickerRoot.vue'

const props = defineProps<GradientPickerPositionInputProps>()

const rootContext = injectGradientPickerContext()

// The selected-stop fallback is only for an omitted stopId. A provided id
// that no longer resolves (stop removed, ids regenerated by a model write)
// must not silently retarget the input — it goes inert instead.
const stop = computed(() =>
  props.stopId !== undefined
    ? rootContext.stops.value.find((s) => s.id === props.stopId) ?? null
    : rootContext.selectedStop.value
)

const isDisabled = computed(() => rootContext.disabled.value || stop.value === null)

function commit (event: Event) {
  const current = stop.value
  if (!current) return
  const target = event.target as HTMLInputElement
  const match = target.value.trim().match(/^(-?\d+(?:\.\d+)?)\s*%?$/)
  if (match) {
    const value = clampPosition(parseFloat(match[1]!))
    // Written back by hand: when the clamped value equals the current one the
    // binding has nothing to patch, yet the field may show the raw text.
    target.value = `${value}%`
    // Only a genuine change moves the stop and commits; re-parsing canonical
    // text (blur after Enter, or an untouched field) is a no-op.
    if (value !== current.position) {
      rootContext.moveStop(current.id, value)
      rootContext.commitValue()
    }
  } else {
    target.value = `${current.position}%`
  }
}

const ui = rootContext.uiSlots('input')
</script>

<template>
  <div
    :data-disabled="isDisabled ? '' : undefined"
    :class="ui.group(props.ui?.group, props.class)"
  >
    <div :class="ui.item(props.ui?.item)">
      <input
        type="text"
        inputmode="numeric"
        :aria-label="props.label ?? 'Stop position'"
        :disabled="isDisabled"
        :value="stop === null ? '' : `${stop.position}%`"
        :class="ui.field(props.ui?.field)"
        @blur="commit"
        @keydown.enter.prevent="commit"
      >
    </div>
  </div>
</template>
